### PR TITLE
Fixing pytest-bdd/tests multiple scenarios passing due to syntax errors.

### PR DESCRIPTION
**Pull request by 1Mark**
Basket should output a fixture.
Multiline strings are not interpreted as """ when being parsed.
ddg_response should be a fixture.

### CODE REVIEW

**Review by AndyLPK247 — CHANGES_REQUESTED** [review]
If you would like for me to accept your pull request, then please edit the code to be identical to the version found in https://github.com/AndyLPK247/tau-pytest-bdd.

**Comment by 1Mark** [comment]
Ah I didn't realise the reason was https://github.com/AndyLPK247/tau-pytest-bdd#version-4-warning (I just recently started using pytest-bdd) ! And I found this repo via your blogs. Ah well. Hmm, i guess maybe it would be better to just update the readme.md to link to the new repo instead? To avoid requiring to maintain two repos? (If they are the same that is, I haven't checked).

**Comment by AndyLPK247** [comment]
I'm auditing my example projects, and I'll be making updates to this project.

**Comment by AndyLPK247** [comment]
@1Mark, this project should now be fixed. I decided to keep it because it shows unique examples.

**Pull request closed without merging**
